services:
  - type: web
    name: calculatrice
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn calculatrice.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
