# Generated by Django 5.1.3 on 2025-04-13 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatrice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='signe',
        ),
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='expression',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='operation',
            name='resultat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
